### ISSUE TITLE
Error: unable to get the latest version

### ISSUE THREAD

**Issue by blazejszumtink** [arduino/setup-protoc#108]
### Describe the problem

Getting this error:
```
Run arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
  with:
    version: v3.20.3
    include-pre-releases: false
Error: Error: unable to get latest version
```

### To reproduce

Run GH Step:
```
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: v3.20.3

```

### Expected behavior

protoc is setup 

### 'arduino/setup-protoc' version

3.0.0

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [x] I verified the problem still occurs when using the latest version
- [x] My report contains all necessary details
