### ISSUE TITLE
Unable to get latest version

### ISSUE THREAD

**Issue by patrickk** [arduino/setup-protoc#14]
Similar to [this issue](https://github.com/arduino/setup-protoc/issues/11), I'm also getting an "Unable to get latest version" error on the action.

This is my config: 

```
      - name: Install protoc
        uses: arduino/setup-protoc@master
        with:
          version: "3.7.1"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

I see in that other issue that the person has [updated to v1.1.0 and moved it below the checkout step](https://github.com/ahmagdy/k8s-pod-scheduler/blob/master/.github/workflows/go.yml), does this matter? 

Thank you.

**Comment by per1234** [comment]
The problem appears to be that the action does not handle pagination of GitHub API responses. So only the versions of protoc on the first page of results are available from the action.

A fix has been submitted: https://github.com/arduino/setup-protoc/pull/9, but not merged.

If you like, you can use the 3rd party fork with the fix by changing the action name to `solo-io/setup-protoc@master`:
```yaml
      - name: Install protoc
        uses: solo-io/setup-protoc@master
        with:
          version: "3.7.1"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
I just gave it a try and it fixes that "Unable to get latest version" error for me with protoc 3.7.1.
