### ISSUE TITLE
Install can fail if GitHub API limit is reached

### ISSUE THREAD

**Issue by NfNitLoop** [arduino/setup-protoc#18]
It looks like internally, setup-protoc calls GitHub to download releases.

If a build node has been making lots of calls to GitHub already (say, due to someone else previously building on it), then my node can (and did) fail due to hitting GitHub's API limit for unauthenticated requests.

![image](https://user-images.githubusercontent.com/339075/108560600-dac42e80-72b1-11eb-829c-56b9645eeaa6.png)

**Comment by NfNitLoop** [comment]
Ah! I was reading docs on other actions and saw them passing GITHUB_TOKEN environment variables.

Sure enough, you already document that in the README.md.  Sorry for the false alarm.

```yaml
- name: Install Protoc
  uses: arduino/setup-protoc@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
```
