### ISSUE TITLE
New protobuf versionning scheme such as 21.1 is not supported

### ISSUE THREAD

**Issue by ajasmin** [arduino/setup-protoc#33]
### Describe the problem

Protobuf has recently changed its versioning scheme. The release after 3.20 is named 21.0.

### To reproduce

Sample workflow:

```
      - name: install protoc
        uses: arduino/setup-protoc@master
        with:
            version: 21.1
```

### Expected behavior

`protoc --version` shows 3.21.1

### 'arduino/setup-protoc' version

v1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
