### ISSUE TITLE
Can't install recent releases

### ISSUE THREAD

**Issue by rotemtam** [arduino/setup-protoc#47]
### Describe the problem

It seems like some recent releases aren't tagged with `semver` compatible tags. E.g: https://github.com/protocolbuffers/protobuf/releases/tag/v21.9

`setup-protoc` currently filters non-semver compatible releases:
https://github.com/protocolbuffers/protobuf/releases/tag/v21.9

Therefore, new versions cannot be installed.

### To reproduce

```yaml
- name: Install Protoc
  uses: arduino/setup-protoc@v1
  with:
    version: '21.9'

```

### Expected behavior

v21.9 installed

### 'arduino/setup-protoc' version

v1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
