### ISSUE TITLE
[error] API rate limit exceeded for 199.7.166.17.

### ISSUE THREAD

**Issue by huan** [arduino/setup-protoc#6]
```
Run arduino/setup-protoc@master
  with:
    version: 3.x
    include-pre-releases: false
  env:
    GOROOT: /Users/runner/hostedtoolcache/go/1.14.2/x64
##[error]API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

It happens in my GitHub Actions at <https://github.com/Chatie/grpc/runs/602856184?check_suite_focus=true#step:5:7>

**Comment by per1234** [comment]
You can avoid this by providing a personal access token to the action via the `repo-token` input. GitHub Actions automatically generates a token, which is accessible via the [`GITHUB_TOKEN` secret](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret).

So you only need to change your "Install Protoc" step to:
```yaml
    - name: Install Protoc
      uses: arduino/setup-protoc@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```
