### ISSUE TITLE
Not running on windows-latest Github runner

### ISSUE THREAD

**Issue by vinothsparrow** [arduino/setup-protoc#83]
### Describe the problem

Getting this error while running on windows Github runner

```Error: Error: Unable to locate executable file: powershell. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.``` 

<img width="1705" alt="Screenshot 2023-05-31 at 2 34 44 PM" src="https://github.com/arduino/setup-protoc/assets/3402812/7075c2d1-ef69-4045-94f9-b2c68c8c2c1c">

### To reproduce

```yml
name: Dev
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs & yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
       - name: Install Protoc
         uses: arduino/setup-protoc@v2
         with:
          version: "23.x"
```

### Expected behavior

step successful

### 'arduino/setup-protoc' version

2.0.0

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
