### ISSUE TITLE
Unable to install protoc windows on self hosted runner

### ISSUE THREAD

**Issue by DaMandal0rian** [arduino/setup-protoc#86]
### Describe the problem

Getting this error while running on windows Github self hosted runner

```Run arduino/setup-protoc@v1.3.0
Getting protoc version: v3.20.3
Downloading archive: https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-win64.zip
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\actions-runner\_work\_temp\59c9dc7a-467b-4602-b4fa-a3da5a3715[12](https://github.com/subspace/subspace-cli/actions/runs/5464647826/jobs/9946965475#step:4:13)' -DestinationPath 'C:\actions-runner\_work\_temp\569b9470-8294-47c6-943c-83f97b52d157' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\actions-runner\_work\_temp\59c9dc7a-467b-4602-b4fa-a3da5a371512', 'C:\actions-runner\_work\_temp\569b9470-8294-47c6-943c-83f97b52d157', $true) }"

Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\actions-runner\_work\_tem ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
 
Error: Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

### To reproduce
```
runs-on:` ${{ matrix.os }}
    steps:
      - name: git checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # @v3.1.0

      # On macOS, we need a proper Clang version, not Apple's custom version without wasm32 support
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@8852e4d5c58653ed05135c0a5d949d9c2febcb00 # v1.6.1
        with:
          version: "15.0"
        if: runner.os == 'macOS'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1.3.0
        with:
          version: "3.20.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

### Expected behavior

step successful

### 'arduino/setup-protoc' version

v1.3.0, v2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-protoc/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
